import Header from "@components/Header/Header";
import { EpisodeResponse, LocationResponse } from "@types";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
export const LocationPage = (props: LocationResponse) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Worlds</h1>
      <ul>
        {props.results.map((location) => {
          return (
            <li key={location.id}>
              <a onClick={() => router.push(`/location/${location.id}`)}>
                <figure>
                  <figcaption>
                    <h1>{location.name}</h1>
                    {location.dimension !== "unknown" ? (
                      <h3>{location.dimension}</h3>
                    ) : null}
                  </figcaption>
                </figure>
              </a>
            </li>
          );
        })}
      </ul>
    </>
  );
};
export const getServerSideProps = async () => {
  const res = await fetch("https://rickandmortyapi.com/api/location");
  /* const res = await fetch("https://rickandmortyapi.com/api/location");
    const res = await fetch("https://rickandmortyapi.com/api/location"); */
  const locations: LocationResponse = await res.json();
  return { props: locations };
};
export default LocationPage;
