import Head from "next/head";
import styles from "@styles/Home.module.css";
import { useRouter } from "next/router";
import { CharacterResponse } from "@types";

const Home = (props: CharacterResponse) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          <button onClick={() => router.push("/episode")}>Episodes</button>
          <button onClick={() => router.push("/character")}>Characters</button>
          <button onClick={() => router.push("/location")}>Locations</button>
        </section>
      </main>
    </>
  );
};

export default Home;
